#!/usr/bin/python3
import argparse
from PIL import Image, ImageDraw, ImageFont
from picamera import PiCamera
import actfw
from actfw.task import Consumer

(CAPTURE_WIDTH, CAPTURE_HEIGHT) = (320, 240) # capture image size
(DISPLAY_WIDTH, DISPLAY_HEIGHT) = (640, 480) # display area size

class Presenter(Consumer):

    def __init__(self, settings, camera, cmd):
        super(Presenter, self).__init__()
        self.settings = settings
        self.camera = camera
        self.cmd = cmd
        self.font = ImageFont.truetype(font='/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf', size=18)
        if self.settings['display']:
            self.display = actfw.Display(camera, (DISPLAY_WIDTH, DISPLAY_HEIGHT))

    def proc(self, frame):
        image = Image.frombuffer('RGB', (CAPTURE_WIDTH, CAPTURE_HEIGHT), frame.getvalue(), 'raw', 'RGB')
        self.cmd.update_image(image) # update `Take Photo` image
        actfw.notice([{'test':True}])
        if self.settings['display']:
            draw = ImageDraw.Draw(image)
            draw.text((0,0), 'Hello, Actcast!', font = self.font, fill = (0,255,0))
            self.display.update((0, 0, DISPLAY_WIDTH, DISPLAY_HEIGHT), image.tobytes(), (CAPTURE_WIDTH, CAPTURE_HEIGHT), 'rgb')

def main(args):

    # Create picamera object
    camera = PiCamera()
    camera.resolution = (CAPTURE_WIDTH, CAPTURE_HEIGHT)
    camera.framerate = 30

    # Actcast application
    app = actfw.Application()

    # Load act setting
    settings = app.get_settings({'display': True})

    # CommandServer (for `Take Photo` command)
    cmd = actfw.CommandServer()
    app.register_task(cmd)

    # Capture task
    cap = actfw.capture.PiCameraCapture(camera, format='rgb', use_video_port=True)
    app.register_task(cap)

    # Presentation task
    pres = Presenter(settings, camera, cmd)
    app.register_task(pres)

    # Make task connection from 'cap' to 'pres'
    cap.connect(pres)

    # Start application
    app.run()

if __name__=='__main__':
    parser = argparse.ArgumentParser(description='example: Hello, Actcast!')
    main(parser.parse_args())
