version: 2
jobs:
  build-wheel:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install python dev tools
          command: |
            apt-get update
            apt-get install -y ca-certificates python3-wheel python3-setuptools
            python3 setup.py bdist_wheel
      - store_artifacts:
          path: /root/project/dist/actfw-1.0.1-py3-none-any.whl
          destination: actfw-1.0.1-py3-none-any.whl

workflows:
  version: 2
  commit:
    jobs:
      - build-wheel
