version: 2
jobs:
  build-wheel:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install python dev tools
          command: |
            apt-get update
            apt-get install -y ca-certificates python3-wheel python3-setuptools python3-pip
      - run:
          name: Check code format
          command: |
            pip3 install autopep8
            [ $(autopep8 --diff --max-line-length 128 -r . | wc -l) = 0 ]
      - run:
          name: Make wheel
          command: |
            python3 setup.py bdist_wheel
      - run:
          name: Put artifacts
          command: |
            mkdir /root/artifacts
            mv /root/project/dist/*.whl /root/artifacts/
      - store_artifacts:
          path: /root/artifacts
          destination: artifacts
      - run:
          name: Documentation
          command: |
            pip3 install sphinx
            pip3 install sphinx_theme
            python3 setup.py build_sphinx
            tar cvjf build/sphinx/html.tar.bz2 -C build/sphinx html
      - store_artifacts:
          path: build/sphinx/html
          destination: html
      - store_artifacts:
          path: build/sphinx/html.tar.bz2
          destination: html.tar.bz2

workflows:
  version: 2
  commit:
    jobs:
      - build-wheel
