version: 2
jobs:
  build-wheel:
    docker:
      - image: python:3-buster
    steps:
      - checkout
      - run:
          name: Install python dev tools
          command: |
            apt-get update
            apt-get install -y ca-certificates python3-pip
            pip3 install pipenv
            pipenv install --dev -e .
      - run:
          name: Check code format
          command: |
            [ $(pipenv run autopep8 --diff --max-line-length 128 -r . | wc -l) = 0 ]
      - run:
          name: Make wheel
          command: |
            pipenv run python setup.py bdist_wheel
      - run:
          name: Put artifacts
          command: |
            mkdir /root/artifacts
            mv /root/project/dist/*.whl /root/artifacts/
      - store_artifacts:
          path: /root/artifacts
          destination: artifacts
      - run:
          name: Documentation
          command: |
            pipenv run sphinx-build docs build/sphinx/html
            tar cvjf build/sphinx/html.tar.bz2 -C build/sphinx html
      - store_artifacts:
          path: build/sphinx/html
          destination: html
      - store_artifacts:
          path: build/sphinx/html.tar.bz2
          destination: html.tar.bz2

workflows:
  version: 2
  commit:
    jobs:
      - build-wheel
